#!/bin/bash
# Hopsan TLM start-up script
# Start with 6 arguments:
# 1 XModelName (XModel directory) 
# 2 start-time 
# 3 end-time 
# 4 max-time-step 
# 5 server-name:port 
# 6 FMU file 

# *********************SETUP SIMULATION*********************************************
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$OMTLMSimulatorPath/bin

DIR=$1

case $1 in
  /*) DIR=$1 ;;
  *) DIR=$PWD/$1 ;;
esac


FMIWrapper_Cmd="FMIWrapper $DIR $6 solver=CVODE -d -v $^"

TLMCONFIGFILE=tlm.config

if [ ! -f "$1/$6" ] ; then 
    if [ ! -f "$6" ] ; then 
	echo Usage: 
	echo $0 XModelName start-time end-time max-time-step server-name:port model-file 
	echo $6
	pwd
	exit 1
    fi
fi

mkdir $1
echo execution directory is $1
cd $1

echo Starting an FMIWrapper simulation with input file: $6
echo Make sure that: 
echo time = $2
echo timeEnd = $3
echo MaxTimeStep "<"= $4
echo 

echo Writing caseID $1 and server name $5 to file $TLMCONFIGFILE
echo $1 > $TLMCONFIGFILE 
echo $5 >> $TLMCONFIGFILE
echo $2 >> $TLMCONFIGFILE
echo $3 >> $TLMCONFIGFILE
echo $4 >> $TLMCONFIGFILE

echo Starting FMIWrapper
echo $FMIWrapper_Cmd
echo DOING THIS: $FMIWrapper_Cmd > $1.simlog
$FMIWrapper_Cmd
echo DONE THIS: $FMIWrapper_Cmd > $1.simlog
