#!/bin/bash
# OMFMISimulatorWrapper TLM start-up script
# Start with 6 arguments:
# 1 XModelName (XModel directory) 
# 2 start-time 
# 3 end-time 
# 4 max-time-step 
# 5 server-name:port 
# 6 XML file 

# *********************SETUP SIMULATION*********************************************
export LD_LIBRARY_PATH=$OMFMISimulatorPath/install/lib:$LD_LIBRARY_PATH

echo LD_LIBRARY_PATH: $LD_LIBRARY_PATH

OMFMISimulatorWrapper_Cmd="OMFMISimulatorWrapper $PWD/$1 $6"

TLMCONFIGFILE=tlm.config

if [ ! -f "$1/$6" ] ; then 
    if [ ! -f "$1/$6.mo" ] ; then 
	echo Usage: 
	echo $0 XModelName start-time end-time max-time-step server-name:port model-file 
	echo $6
	pwd
	exit 1
    fi
fi

echo execution directory is $1
cd $1

echo Starting an OMFMISimulatorWrapper simulation with input file: $6
echo Make sure that: 
echo time = $2
echo timeEnd = $3
echo MaxTimeStep "<"= $4
echo 

echo Writing caseID $1 and server name $5 to file $TLMCONFIGFILE
echo $1 > $TLMCONFIGFILE 
echo $5 >> $TLMCONFIGFILE
echo $2 >> $TLMCONFIGFILE
echo $3 >> $TLMCONFIGFILE
echo $4 >> $TLMCONFIGFILE

echo Starting OMFMISimulatorWrapper
echo DOING THIS: $OMFMISimulatorWrapper_Cmd > $1.simlog
$OMFMISimulatorWrapper_Cmd
echo DONE THIS: $OMFMISimulatorWrapper_Cmd > $1.simlog
